language: cpp

os: linux

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .

os: windows

script:
    - mkdir build-windows
    - cd build-windows
    - cmake ..
    - cmake --build .

