name: CI

on: [push]

jobs:
  build:    
    
    strategy:
      matrix:
        foo: [windows-latest]
        
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        pip install conan
        mkdir build
        cd build
        conan install ..
    - name: configure
      run: |
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        cmake --build .
    - name: deploy
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: build/bin
        
