name: CI

on: [push]

jobs:

        
  build:    
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: append to path
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "::add-path::~/.local/bin/"
    - name: install dependencies
      run: |
        pip install conan
        mkdir build
        cd build
        conan install ..
    - name: configure
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: |
        cd build
        cmake --build . --parallel --config Release
    - name: pack
      if: matrix.os != 'windows-latest'
      run: |
        cd build
        cpack --version
        cpack
    - name: pack
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        C:\/Program Files/CMake/bin/cpack.exe --version
    - name: deploy
      uses: actions/upload-artifact@v1
      with:
        name: bin-${{ matrix.os }}
        path: build/test-travis.zip

          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: redploy
        uses: actions/download-artifact@v1
        with:
          name: bin-ubuntu-latest
