name: CI

on: [push]

jobs:
  build:    
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: append to path
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "::add-path::~/.local/bin/"
    - name: install dependencies
      run: |
        sudo pip install conan
        mkdir build
        cd build
        conan install ..
    - name: configure
      run: |
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        cmake --build .
    - name: deploy
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: build/bin
        
