name: CI

on: [push]

jobs:
  build:    
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        conan_path: [conan]
        include:
          - os: ubuntu-latest
            conan_path: ~/.local/bin/conan
        
    

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo pip install conan
        mkdir build
        cd build
        ${{ conan_path }} install ..
    - name: configure
      run: |
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        cmake --build .
    - name: deploy
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: build/bin
        
